# Beta values for jotunheimr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# app name
fullnameOverride: "jotunheimr"

# deployment spec
replicaCount: 1
restartPolicy: Always

# autoscaling
autoscaling: 
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

# pod disruption budget
disruptionBudget:
  enabled: false
  minAvailable: 1

# containers
containers:
  - name: jotunheimr
    image: eu.gcr.io/dnt-docker-registry-public/jotunheimr
    tag: ""
    pullPolicy: IfNotPresent
    environment:
      NODE_ENV: "production"
      VIRTUAL_HOST: "https://jotunheimr.app.dnt.no,http://jotunheimr.app.dnt.no"
      VIRTUAL_PORT: "8080"
      ALLOW_ORIGINS: "tur.app.dnt.no,hytte.app.dnt.no,tur.app.dnt.local,hytte.app.dnt.local,sjekkut.app.dnt.no,sjekkut.app.dnt.local,urdr.app.dnt.local"
      AWS_ACCESS_KEY_ID: ""
      AWS_BUCKET_NAME: "jotunheimr"
      AWS_BUCKET_PATH: "prod/"
      AWS_BUCKET_REGION: "eu-west-1"
      AWS_SECRET_ACCESS_KEY: ""
      FORCE_SSL: true
      HSTS_MAX_AGE: 31536000
      LIBRATO_PREFIX: "jotunheimr."
      LIBRATO_TOKEN: ""
      LIBRATO_USER: "ali.kaafarani@dnt.no"
      NEW_RELIC_APP_NAME: "Jotunheimr"
      NEW_RELIC_LICENSE_KEY: ""
      NEW_RELIC_LOG: "stdout"
      NEW_RELIC_NO_CONFIG_FILE: "true"
      SENTRY_DNS: ""
      SENTRY_DSN: ""
      STATSD_HOST: "statsd"
      STATSD_PORT: 8125
      VIRTUAL_HOST_WEIGHT: 20
    ports:
      - name: "http"
        containerPort: 8080
        protocol: TCP
    resources:
      limits:
        cpu: 250m
        memory: 768Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi

nodeSelector: {}

affinity: {}

tolerations: []


# services
services:
  - name: jotunheimr
    expandName: true
    type: ClusterIP
    port: 8080

ingress:
  # Used to create an Ingress record.
  enabled: true
  hosts:
    - host: jotunheimr.beta.dnt.org
      paths:
        - path: /
          serviceName: jotunheimr
          servicePort: 8080
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m

  tls:
    - secretName: beta-dnt-org-tls
      hosts:
        - jotunheimr.beta.dnt.org
cert:
  enabled: false
  issuer: "letsencrypt-production"