// Generated by CoffeeScript 1.10.0
var Client;

Client = require('librato');

module.exports = new Client(process.env.LIBRATO_USER, process.env.LIBRATO_TOKEN, {
  prefix: process.env.LIBRATO_PREFIX,
  source: process.env.DOTCLOUD_SERVICE_ID || 'test'
});

module.exports.logRequest = function(method) {
  return module.exports.measure('http.request', 1, {
    source: method
  });
};

module.exports.logResponse = function(status) {
  return module.exports.measure('http.response', 1, {
    source: '' + status
  });
};

module.exports.logImageUpload = function() {
  return module.exports.measure('image.upload', 1, {});
};

module.exports.logImageProcessingTime = function(t1, t2) {
  return module.exports.measure('image.processing', t2 - t1, {});
};
