// Generated by CoffeeScript 1.10.0
var Client;

Client = require('raven').Client;

Client.prototype.captureHeaderSent = function(req, files) {
  return this.captureMessage("Headers already sent", {
    level: 'error',
    extra: {
      req: req,
      files: files
    }
  });
};

Client.prototype.captureResClose = function(req) {
  return this.captureMessage("Response was closed", {
    level: 'warning',
    extra: {
      req: req
    }
  });
};

module.exports = new Client(process.env.SENTRY_DNS);

if (process.env.SENTRY_DNS) {
  module.exports.patchGlobal(function(id, err) {
    console.error('Uncaught Exception');
    console.error(err.message);
    console.error(err.stack);
    return process.exit(1);
  });
}
